
name: Tarea TP Biblioteca Digital
description: Crear una nueva tarea vinculada a un milestone y al project correspondiente.


title: "[Tarea] "
labels: ["tarea"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Completa los siguientes campos para registrar esta tarea correctamente.**  

  - type: input
    id: objetivo
    attributes:
      label: Objetivo
      description: ¿Qué se busca lograr con esta tarea?
l
      placeholder: Crear clase Usuario con atributos básicos
    validations:
      required: true

  - type: textarea
    id: detalles
    attributes:
      label: Detalles de implementación
      description: Explicá brevemente los pasos o componentes involucrados.
      placeholder: |
        - Crear clase Usuario
        - Agregar constructor
        - Implementar getters y setters
        - Probar en Consola o clase Main

    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Etapa / Milestone
      description: Seleccioná a qué etapa del trabajo pertenece esta tarea
      options:
        - Etapa 1 - Diseño Base y Principios SOLID
        - Etapa 2 - Gestión de Recursos y Colecciones
        - Etapa 3 - Sistema de Préstamos y Reservas
        - Etapa 4 - Reportes y Análisis

    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist de finalización
      description: Marcá los puntos que se deben cumplir para dar la tarea como terminada.
      options:
        - label: La tarea está implementada correctamente.
        - label: La funcionalidad fue probada desde Consola o Main.
        - label: Se creó una rama específica para esta tarea.
        - label: Se abrió un Pull Request que menciona este Issue.

